export type PortfolioSeedHolding = {
  stockName: string;
  exchangeCode: string;
  yahooSymbol: string;
  googleSymbol: string;
  qty: number;
  purchasePrice: number;
  sector: string;
  fallbackCmp: number;
  fallbackPeRatio: number | null;
  fallbackLatestEarnings: string;
};

export const portfolioSeedHoldings: PortfolioSeedHolding[] = [
  {
    stockName: "HDFC Bank",
    exchangeCode: "NSE:HDFCBANK",
    yahooSymbol: "HDFCBANK.NS",
    googleSymbol: "HDFCBANK:NSE",
    qty: 120,
    purchasePrice: 1460,
    sector: "Banking",
    fallbackCmp: 1684,
    fallbackPeRatio: 19.7,
    fallbackLatestEarnings: "Q4 beat estimates",
  },
  {
    stockName: "ICICI Bank",
    exchangeCode: "NSE:ICICIBANK",
    yahooSymbol: "ICICIBANK.NS",
    googleSymbol: "ICICIBANK:NSE",
    qty: 150,
    purchasePrice: 985,
    sector: "Banking",
    fallbackCmp: 1248,
    fallbackPeRatio: 18.5,
    fallbackLatestEarnings: "Margins stable",
  },
  {
    stockName: "Kotak Bank",
    exchangeCode: "NSE:KOTAKBANK",
    yahooSymbol: "KOTAKBANK.NS",
    googleSymbol: "KOTAKBANK:NSE",
    qty: 90,
    purchasePrice: 1800,
    sector: "Banking",
    fallbackCmp: 1711,
    fallbackPeRatio: 17.4,
    fallbackLatestEarnings: "Muted loan growth",
  },
  {
    stockName: "Infosys",
    exchangeCode: "NSE:INFY",
    yahooSymbol: "INFY.NS",
    googleSymbol: "INFY:NSE",
    qty: 160,
    purchasePrice: 1360,
    sector: "Technology",
    fallbackCmp: 1528,
    fallbackPeRatio: 24.2,
    fallbackLatestEarnings: "Deal wins strong",
  },
  {
    stockName: "TCS",
    exchangeCode: "NSE:TCS",
    yahooSymbol: "TCS.NS",
    googleSymbol: "TCS:NSE",
    qty: 95,
    purchasePrice: 3415,
    sector: "Technology",
    fallbackCmp: 3926,
    fallbackPeRatio: 29.3,
    fallbackLatestEarnings: "Attrition eased",
  },
  {
    stockName: "Persistent Systems",
    exchangeCode: "NSE:PERSISTENT",
    yahooSymbol: "PERSISTENT.NS",
    googleSymbol: "PERSISTENT:NSE",
    qty: 30,
    purchasePrice: 1660,
    sector: "Technology",
    fallbackCmp: 4145,
    fallbackPeRatio: 66.4,
    fallbackLatestEarnings: "Guidance raised",
  },
  {
    stockName: "Reliance",
    exchangeCode: "NSE:RELIANCE",
    yahooSymbol: "RELIANCE.NS",
    googleSymbol: "RELIANCE:NSE",
    qty: 115,
    purchasePrice: 2850,
    sector: "Energy",
    fallbackCmp: 2720,
    fallbackPeRatio: 26.1,
    fallbackLatestEarnings: "Retail soft patch",
  },
  {
    stockName: "ONGC",
    exchangeCode: "NSE:ONGC",
    yahooSymbol: "ONGC.NS",
    googleSymbol: "ONGC:NSE",
    qty: 420,
    purchasePrice: 191,
    sector: "Energy",
    fallbackCmp: 125,
    fallbackPeRatio: 8.7,
    fallbackLatestEarnings: "Realization pressure",
  },
  {
    stockName: "ITC",
    exchangeCode: "NSE:ITC",
    yahooSymbol: "ITC.NS",
    googleSymbol: "ITC:NSE",
    qty: 410,
    purchasePrice: 432,
    sector: "Consumer",
    fallbackCmp: 454,
    fallbackPeRatio: 27.8,
    fallbackLatestEarnings: "FMCG steady",
  },
  {
    stockName: "Asian Paints",
    exchangeCode: "NSE:ASIANPAINT",
    yahooSymbol: "ASIANPAINT.NS",
    googleSymbol: "ASIANPAINT:NSE",
    qty: 55,
    purchasePrice: 3035,
    sector: "Consumer",
    fallbackCmp: 3298,
    fallbackPeRatio: 56.2,
    fallbackLatestEarnings: "Volume recovery",
  },
  {
    stockName: "Titan",
    exchangeCode: "NSE:TITAN",
    yahooSymbol: "TITAN.NS",
    googleSymbol: "TITAN:NSE",
    qty: 78,
    purchasePrice: 3120,
    sector: "Consumer",
    fallbackCmp: 3672,
    fallbackPeRatio: 78.1,
    fallbackLatestEarnings: "Jewellery growth solid",
  },
  {
    stockName: "Nestle India",
    exchangeCode: "NSE:NESTLEIND",
    yahooSymbol: "NESTLEIND.NS",
    googleSymbol: "NESTLEIND:NSE",
    qty: 52,
    purchasePrice: 2240,
    sector: "Consumer",
    fallbackCmp: 3303,
    fallbackPeRatio: 73.8,
    fallbackLatestEarnings: "Premium mix improving",
  },
];
